---
- hosts: localhost
  remote_user: root
  tasks:
    - name: install puppet-root authorized_key file
      authorized_key:
        user: root
        state: present
        key: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDDa7mZa6fNlGlqZN6KIry3+UwyheAyiKrn8HsAaQCcxBPJSaye4CE4oSrGXvv61xPGdhkOFPqhJZ94qdNFgw64k994MOZBGLC46EacZvejaup8VKYhSLCTfi3kiK+c4KXZ8BSp9G2pjN0C1m2XetzqYPITjWOkHtjq0G5CJl/mTQowpiFWlcfutwkHE1Fax8GTFnMPcOG2klbfiWW9lKpSbu7E/eTiZ06S3UaawNBv0rxEL71sNs4oGhlgquHM1pAnkg6muxB4qM/tXD3mR1LnYhCwFTobu6TkFPIrg+nk+ie7PmDDYkR2EDfUL4zB+fXvl89A/4y4vnZijfFGSUkqBwMEAywSEckBcHRIcmCjCGtjfB8LrgW7T06RhFhH86mQVp7cN5amSpD8s5+0bGK8kkYZQs7vTT1aHh+ERc6AmStrDCmUkcBdqd+ons5dyivMSUkoQI+un4Z8iPAd/189gaM0UWgPmG3IAS/iyBUeRNagt/QwBGwaHDKTYZY3p8iZDrrtQI7aqojACW7zHVd16qoPIFUyL3lVXerHP/ypvfngfV/COZ8TGv5GgcxQU7XPzaNsOazPQewy2FKJcVz3Qb5BZH6SimouG6rKugpEvv82e22lvHF0meJrogSl8J9C1GmVm58AhexZN+PQ2yoDCx4x4hyOeZ26EQ5SoElrvw== root@puppet.arc.rice.edu'
        key_options: 'from="10.128.81.58"'

    - name: install dab11-rsa authorized_key file
      authorized_key:
        user: root
        state: present
        key: https://github.com/rice-acs/ssh-keys/dab11-rsa.pub
        key_options: 'from="168.7.23.162"'

    - name: install dab11 authorized_key file
      authorized_key:
        user: root
        state: present
        key: https://github.com/rice-acs/ssh-keys/dab11.pub
        key_options: 'from="168.7.23.162"'

    - name: install dab11-protected authorized_key file
      authorized_key:
        user: root
        state: present
        key: https://github.com/rice-acs/ssh-keys/dab11-protected.pub

    - name: install burkett-rsa authorized_key file
      authorized_key:
        user: root
        state: present
        key: https://github.com/rice-acs/ssh-keys/burkett-rsa.pub

    - name: install dalton authorized_key file
      authorized_key:
        user: root
        state: present
        key: https://github.com/rice-acs/ssh-keys/jz71-rsa.pub

    - name: install mc76-rsa authorized_key file
      authorized_key:
        user: root
        state: present
        key: https://github.com/rice-acs/ssh-keys/mc76-rsa.pub

    - name: install sep6-rsa authorized_key file
      authorized_key:
        user: root
        state: present
        key: https://github.com/rice-acs/ssh-keys/sep6-rsa.pub

    - name: install sep6 authorized_key file
      authorized_key:
        user: root
        state: present
        key: https://github.com/rice-acs/ssh-keys/sep6.pub

    - name: install ansible-root authorized_key file
      authorized_key:
        user: root
        state: present
        key: https://github.com/rice-acs/ssh-keys/ansible-root.pub

    - name: install kali-root authorized_key file
      authorized_key:
        user: root
        state: present
        key: https://github.com/rice-acs/ssh-keys/kali-root-rsa.pub

